### PR TITLE
feat: added Testimonials

### PR DESCRIPTION
**Pull request by juzhiyuan**
This PR aims to add Testimonials for APi Gateway (mainly on Apache APISIX).

- [x] meicai.cn/Tencent IEG/Tencent Cloud/Airwallex
- [x] i18n

Preview: https://api7-website-git-feat-user-talk-apiseven.vercel.app/zh

### CODE REVIEW

**Comment by juzhiyuan** [comment]
**TODO**

- [ ] Update Logos (some of them are using Chinese in English mode)

**Comment by LiteSun** [comment]
Found bug here: Image and text are not switched at the same time


https://user-images.githubusercontent.com/31329157/116033312-c591c480-a693-11eb-9895-90835d7aefb5.mov

**Comment by juzhiyuan** [comment]
> Found bug here: Image and text are not switched at the same time
> 

Done

**Review by membphis — COMMENTED** [review]
We should allow users to manually click to switch.

**Comment by membphis** [comment]
> We should allow users to manually click to switch.

ping @juzhiyuan

**Comment by juzhiyuan** [comment]
duplicate as #115

**Pull request closed without merging**
