### PR TITLE
docs: added why we need Apache APISIX blog

### PR DESCRIPTION
**Pull request by Serendipity96**
Changes:
docs: added why we need Apache APISIX blog

### CODE REVIEW

**Review by moonming — APPROVED** [review]
do we support `keywords` for SEO?

**Comment by moonming** [comment]
we can also post this blog to apisix.apache.org

**Comment by Serendipity96** [comment]
> do we support `keywords` for SEO?

we need to discuss SEO when we are free.

**Comment by Serendipity96** [comment]
> we can also post this blog to apisix.apache.org

OK.

**Review by juzhiyuan — APPROVED** [review]

**Pull request merged**
