### PR TITLE
docs: added SLA for API7

### PR DESCRIPTION
**Pull request by juzhiyuan**
This PR aims to add SLA for products.

- [x] added Apache APISIX SLA

Preview: https://api7-website-git-feat-sla-apiseven.vercel.app/en/apache-apisix-sla

### CODE REVIEW

**Comment by juzhiyuan** [comment]
The table `Apache APISIX Support Plans` is too narrow to see, need to adjust styles.

**Comment by guoqqqi** [comment]
I think we can increase the width of the parent container as well as change the width of each item of the table to a fixed width.

**Comment by guoqqqi** [comment]
wait for #67 
image

**Comment by juzhiyuan** [comment]
SLA Description is too narrow, let me rethink this case.

**Comment by juzhiyuan** [comment]
Maybe we need to use `Table` elements instead of Markdown here.

**Comment by membphis** [comment]
image

**Comment by juzhiyuan** [comment]
both are not good

**Pull request closed without merging**
