### PR TITLE
fix: home is compatible in IE

### PR DESCRIPTION
**Pull request by guoqqqi**
I will fix the disordered layout issues first, and finally fix the details.

Layout:
- [x] Middle showcases
- [ ] Nav 
- [x] FooterLinks

### CODE REVIEW

**Review by juzhiyuan — APPROVED** [review]

**Comment by moonming** [comment]
@guoqqqi @juzhiyuan not fixed, still has problem in IE

**Comment by guoqqqi** [comment]
> @guoqqqi @juzhiyuan不固定，在IE中仍然有问题

Sorry, I checked it and it was displayed normally during local debugging. There are still some problems in the development environment. Later, I will raise a New PR to fix it. 

Local display： 
Snip20210112_3
Snip20210112_4

**Comment by juzhiyuan** [comment]
@guoqqqi Please find out what happened on the production build when you are free, API7 Dashboard first.

**Comment by moonming** [comment]
any update?

**Comment by juzhiyuan** [comment]
@moonming trying to fix the footer icon days ago here[1], try again?

[1] https://github.com/api7/website/pull/227

**Comment by guoqqqi** [comment]
There is another problem. After the merge, the Nav is not displayed normally, and I will fix it in a new PR.

**Comment by juzhiyuan** [comment]
赶紧修！！

**Pull request merged**
